uploads = []
generated = []

[[outputs]]
id = "Y8nwXjTaD1HrJcXtkgJYL"
uri = "file://mhcard.png"
type = "image"
title = "新アイコン（28×36px、白枚付き茶色長方形）"

[[outputs]]
id = "z2TzGFpSjSzeptheWBXdD"
uri = "file://preview_mhcard.png"
type = "image"
title = "mhcard マーカー プレビュー（マンホール絵柄を大きく）"

[[outputs]]
id = "3o2EGj-LHuEyKkokxp9Op"
uri = "file://preview_mhcard_cluster.png"
type = "image"
title = "mhcard クラスター プレビュー（長方形ゖ1.5倍大）"
